#!/usr/bin/env python3
"""Index a local copy of the official ASD-STE100 PDF for page lookups.

Reads only the PDF's bookmark outline (titles and page numbers) through
`qpdf --json` and writes a page map to ~/.config/asd-ste100/config.yml. No text
of the standard is extracted or stored. ASD-STE100 may not be reproduced
without ASD's written authority, so the skill opens the user's own copy at the
mapped page instead of keeping a copy of the dictionary.

Usage:
    ste-pdf-index.py /path/to/ASD-STE100_ISSUE9.pdf
"""
import json
import os
import re
import shutil
import subprocess
import sys

CONFIG = os.path.expanduser("~/.config/asd-ste100/config.yml")


def outline(pdf):
    if not shutil.which("qpdf"):
        sys.exit("qpdf is required (brew install qpdf)")
    result = subprocess.run(
        ["qpdf", "--json", "--json-key=outlines", "--json-key=pages", pdf],
        capture_output=True, text=True)
    if result.returncode not in (0, 3):  # 3 = warnings only
        sys.exit(f"qpdf failed: {result.stderr.strip()[:300]}")
    data = json.loads(result.stdout)
    index = {page["object"]: number for number, page in enumerate(data["pages"], 1)}

    def page_of(item):
        if item.get("destpageposfrom1"):
            return item["destpageposfrom1"]
        dest = item.get("dest")
        return index.get(dest[0]) if isinstance(dest, list) and dest else None

    def walk(items, path):
        for item in items:
            title = re.sub(r"\s+", " ", item.get("title", "")).strip()
            yield path, title, page_of(item)
            yield from walk(item.get("kids", []), path + [title])

    return walk(data.get("outlines", []), []), len(data["pages"])


def build(pdf):
    entries, total = outline(pdf)
    rules, sections, letters = {}, {}, {}
    root, dictionary_intro, approved_verbs = "", None, None
    for path, title, page in entries:
        if page is None:
            continue
        in_dictionary = any(p.startswith("Part 2") for p in path)
        if not path:
            root = title
        elif m := re.fullmatch(r"Rule (\d+\.\d+)", title):
            rules[m.group(1)] = page
        elif re.fullmatch(r"GR-\d+", title):
            rules[title] = page
        elif m := re.match(r"Section (\d+)\b", title):
            sections[m.group(1)] = page
        elif in_dictionary and re.fullmatch(r"[A-Z]{1,3}", title):
            letters[title] = page
        elif in_dictionary and title == "Introduction":
            dictionary_intro = page
        elif in_dictionary and title.lower().startswith("list of approved verbs"):
            approved_verbs = page
    if not rules or not letters:
        sys.exit("outline has no rule or dictionary bookmarks; is this the official PDF?")
    return root, total, rules, sections, letters, dictionary_intro, approved_verbs


def write(pdf, root, total, rules, sections, letters, intro, verbs):
    os.makedirs(os.path.dirname(CONFIG), exist_ok=True)
    out = ["# Generated by ste-pdf-index.py from the bookmark outline of the user's",
           "# own ASD-STE100 copy. Page numbers only, no text of the standard.",
           "# Keep this file local: do not commit or share it.",
           f"pdf: {json.dumps(os.path.abspath(pdf))}",
           f"edition: {json.dumps(root)}",
           f"pages: {total}",
           "sections:"]
    out += [f'  "{k}": {v}' for k, v in sections.items()]
    out.append("rules:")
    out += [f'  "{k}": {v}' for k, v in rules.items()]
    out.append("dictionary:")
    if intro:
        out.append(f"  introduction: {intro}")
    if verbs:
        out.append(f"  approved_verbs: {verbs}")
    out.append("  letters:")
    out += [f'    "{k}": {v}' for k, v in letters.items()]
    out.append(f"  last_page: {total}")
    with open(CONFIG, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")


def main(argv):
    if len(argv) != 1 or argv[0].startswith("-"):
        print(__doc__.strip())
        return 2
    pdf = argv[0]
    if not os.path.isfile(pdf):
        sys.exit(f"not a file: {pdf}")
    parts = build(pdf)
    write(pdf, *parts)
    print(f"wrote {CONFIG}: {len(parts[2])} rules, {len(parts[4])} dictionary letters")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
